"use client";

import React from "react";
import { ArrowRight, MapPin, Calendar } from "lucide-react";
import ScrollReveal from "@/components/ScrollReveal";

export default function ExperienceSection() {
  const responsibilities = [
    "Built a web application using Laravel and React to deliver data generated by network anomaly detectors.",
    "Modernized the UI of an open-source Webphone for an under-development UC&C (Unified Communications and Collaboration) web application.",
    "Contributed to the core logic of an under-development SCA (Static Code Analysis) web application using OpenGrep and Node.js.",
  ];

  const tags = ["Laravel", "React", "Node.js", "OpenGrep", "Webphone", "PostgreSQL", "REST APIs"];

  return (
    <section id="experience" className="mb-32 max-w-6xl mx-auto px-6 sm:px-8">
      <ScrollReveal direction="up" distance={30} duration={600}>
        <h2 className="font-display text-3xl sm:text-4xl font-extrabold text-white mb-12 tracking-tight">
          Experience
        </h2>
      </ScrollReveal>

      <ScrollReveal direction="up" distance={40} duration={800} delay={150}>
        <div className="max-w-3xl relative border-l border-white/10 ml-2 sm:ml-4">
          {/* Glowing Gradient Line */}
          <div className="absolute left-[-1px] top-0 h-full w-[2px] bg-gradient-to-b from-[#8B5CF6] via-[#8B5CF6]/40 to-transparent pointer-events-none" />

          <div className="relative pl-8 sm:pl-12 pb-8">
            {/* Glowing Violet Marker Dot */}
            <div className="absolute left-[-6px] top-1.5 w-3 h-3 bg-[#8B5CF6] rounded-full shadow-[0_0_12px_rgba(139,92,246,0.9)] ring-4 ring-[#0A0A0A]" />

            {/* Header Info */}
            <div className="flex flex-col sm:flex-row sm:items-baseline justify-between mb-2">
              <h3 className="font-display text-2xl font-bold text-white">
                Software Developer Intern
              </h3>
              <span className="font-mono-tech text-xs text-[#8e9192] flex items-center gap-1 mt-1 sm:mt-0">
                <Calendar className="w-3.5 h-3.5 text-[#8B5CF6]" />
                July 2025 – September 2025
              </span>
            </div>

            <div className="flex items-center gap-4 mb-6">
              <p className="font-sans text-lg font-semibold text-[#8B5CF6]">
                Telkom Indonesia
              </p>
              <span className="text-xs font-mono-tech text-[#8e9192] flex items-center gap-1">
                <MapPin className="w-3.5 h-3.5 text-[#3B82F6]" />
                Bandung, Indonesia
              </span>
            </div>

            {/* Deliverables Panel matching reference2.html */}
            <div className="glass-panel p-6 rounded-xl border-l-4 border-l-[#8B5CF6] mb-6">
              <ul className="space-y-4 font-sans text-sm text-[#c4c7c8]">
                {responsibilities.map((item, idx) => (
                  <li key={idx} className="flex items-start">
                    <ArrowRight className="w-4 h-4 text-[#8B5CF6] mr-3 mt-0.5 shrink-0" />
                    <span className="leading-relaxed">{item}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Tech Chips */}
            <div className="flex flex-wrap gap-2">
              {tags.map((tag) => (
                <span
                  key={tag}
                  className="px-3 py-1 rounded-md font-mono-tech text-xs bg-white/5 border border-white/10 text-[#c4c7c8]"
                >
                  {tag}
                </span>
              ))}
            </div>

          </div>
        </div>
      </ScrollReveal>
    </section>
  );
}


