"use client";

import React, { useState } from "react";
import { ArrowUpRight, X, UserCheck, Calendar, CheckCircle, Image as ImageIcon } from "lucide-react";
import ScrollReveal from "@/components/ScrollReveal";

interface ProjectItem {
  id: string;
  label: string;
  title: string;
  role: string;
  timeline: string;
  description: string;
  image?: string;
  additionalContext?: string;
  contributions?: string[];
  tech: string[];
  accentColor: string;
  bgGradient: string;
}

export default function ProjectsSection() {
  const [selectedProject, setSelectedProject] = useState<ProjectItem | null>(null);

  const projects: ProjectItem[] = [
    {
      id: "diagram-coffee",
      label: "UNDERGRADUATE THESIS",
      title: "Diagram Coffee E-Commerce",
      role: "Backend Developer",
      timeline: "February 2026 – August 2026",
      image: "https://assets.salharits.me/Screenshot%202026-07-10%20171335.png",
      description:
        "An e-commerce website for Diagram Coffee featuring a personalized recommendation system designed to maximize upselling opportunities and enhance product discovery.",
      contributions: [
        "Designed and configured the database schema.",
        "Built the core backend application system.",
        "Developed admin and multi-branch management functionality.",
        "Implemented transaction data transfer between primary backend and recommendation system.",
        "Integrated the backend with Xendit payment gateway.",
      ],
      tech: ["Laravel", "MySQL", "RESTful API", "Xendit", "Antigravity"],
      accentColor: "#D97706",
      bgGradient: "from-[#D97706]/15 via-transparent to-transparent",
    },
    {
      id: "netlyzer",
      label: "INTERNSHIP PROJECT",
      title: "Netlyzer",
      role: "Fullstack Developer",
      timeline: "July 2025 – September 2025",
      image: "https://assets.salharits.me/Screenshot%202025-08-22%20130856.png",
      description:
        "A web application designed to visualize data generated by a Network Anomaly Detector.",
      additionalContext:
        "This web project was developed under the direct guidance of the field supervisor at Telkom Indonesia.",
      contributions: [
        "Parsed real-time network anomaly telemetry datasets into structured dashboard charts.",
        "Engineered responsive React frontend with optimized PostgreSQL backend queries.",
        "Built administrative alert dashboard for network diagnostics.",
      ],
      tech: ["React", "Laravel", "PostgreSQL", "RESTful API"],
      accentColor: "#3B82F6",
      bgGradient: "from-[#3B82F6]/15 via-transparent to-transparent",
    },
    {
      id: "cleanquest",
      label: "CAPSTONE PROJECT",
      title: "CleanQuest",
      role: "Fullstack Developer",
      timeline: "February 2025 – July 2025",
      image: "https://assets.salharits.me/Untitled%20design%20(1)%20(1).png",
      description:
        "A gamified mobile application designed to encourage environmental responsibility by assigning daily cleanliness-related tasks and offering rewards, with the goal of cultivating long-term eco-friendly behaviors within communities.",
      contributions: [
        "Built the mobile Dashboard page architecture.",
        "Built the Task Submission & verification mechanism.",
        "Integrated Flutter mobile frontend with RESTful Laravel backend APIs.",
      ],
      tech: ["Flutter", "Laravel", "RESTful API", "MySQL"],
      accentColor: "#10B981",
      bgGradient: "from-[#10B981]/15 via-transparent to-transparent",
    },
  ];

  return (
    <section id="projects" className="mb-32 max-w-6xl mx-auto px-6 sm:px-8">

      {/* Section Headline */}
      <ScrollReveal direction="up" distance={30} duration={600}>
        <h2 className="font-display text-3xl sm:text-4xl font-extrabold text-white mb-12 tracking-tight">
          Selected Projects
        </h2>
      </ScrollReveal>

      {/* Editorial Case Studies Stack */}
      <div className="space-y-10">
        {projects.map((proj, idx) => (
          <ScrollReveal
            key={proj.id}
            direction="up"
            distance={40}
            duration={750}
            delay={idx * 120}
          >
            <div
              onClick={() => setSelectedProject(proj)}
              className="glass-panel glass-panel-hover p-8 rounded-3xl cursor-pointer group relative overflow-hidden transition-all duration-300 border border-white/10"
            >
              {/* Background Glow */}
              <div
                className={`absolute top-0 right-0 w-80 h-80 rounded-full blur-3xl opacity-20 pointer-events-none bg-gradient-to-bl ${proj.bgGradient}`}
              />

              <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6 relative z-10">

                {/* Meta & Main Details */}
                <div className="max-w-2xl space-y-4">
                  <div className="flex flex-wrap items-center gap-3">
                    <span
                      className="font-mono-tech text-xs font-semibold uppercase px-3 py-1 rounded-md border"
                      style={{
                        color: proj.accentColor,
                        borderColor: `${proj.accentColor}40`,
                        backgroundColor: `${proj.accentColor}10`,
                      }}
                    >
                      {proj.label}
                    </span>
                    <span className="font-mono-tech text-xs text-[#8e9192]">
                      {proj.role} • {proj.timeline}
                    </span>
                  </div>

                  <h3 className="font-display text-2xl sm:text-3xl font-extrabold text-white group-hover:text-[#3B82F6] transition-colors">
                    {proj.title}
                  </h3>

                  <p className="font-sans text-base text-[#c4c7c8] leading-relaxed">
                    {proj.description}
                  </p>

                  {proj.additionalContext && (
                    <p className="font-sans text-xs italic text-[#8e9192]">
                      {proj.additionalContext}
                    </p>
                  )}

                  {/* Tech Badges */}
                  <div className="flex flex-wrap gap-2 pt-2">
                    {proj.tech.map((t) => (
                      <span
                        key={t}
                        className="font-mono-tech text-xs px-3 py-1 rounded-md bg-white/5 border border-white/10 text-[#c4c7c8]"
                      >
                        {t}
                      </span>
                    ))}
                  </div>
                </div>

                {/* Action Button */}
                <div className="flex items-center gap-2 font-sans font-semibold text-sm text-white group-hover:text-[#3B82F6] transition-colors shrink-0">
                  <span>View Case Study</span>
                  <ArrowUpRight className="w-5 h-5 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" />
                </div>

              </div>
            </div>
          </ScrollReveal>
        ))}
      </div>


      {/* Interactive Project Detail Modal */}
      {selectedProject && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/80 backdrop-blur-md">
          <div
            className="glass-panel p-6 sm:p-10 rounded-3xl max-w-4xl w-full max-h-[90vh] overflow-y-auto relative border border-white/15 shadow-2xl space-y-6"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Close Button */}
            <button
              onClick={() => setSelectedProject(null)}
              className="absolute top-6 right-6 p-2 rounded-full bg-white/5 hover:bg-white/15 text-[#c4c7c8] hover:text-white transition-colors z-20"
            >
              <X className="w-5 h-5" />
            </button>

            {/* Modal Header */}
            <div>
              <span
                className="font-mono-tech text-xs font-bold uppercase px-3 py-1 rounded-md border inline-block mb-3"
                style={{
                  color: selectedProject.accentColor,
                  borderColor: `${selectedProject.accentColor}40`,
                  backgroundColor: `${selectedProject.accentColor}10`,
                }}
              >
                {selectedProject.label}
              </span>
              <h3 className="font-display text-2xl sm:text-3xl font-extrabold text-white">
                {selectedProject.title}
              </h3>
            </div>

            {/* 1900x868 (Aspect Ratio 50:23) Image Slot Under Title */}
            <div className="w-full aspect-[50/23] rounded-2xl overflow-hidden relative border border-white/10 bg-[#101014] flex items-center justify-center group/media shadow-lg">
              {selectedProject.image ? (
                <img
                  src={selectedProject.image}
                  alt={selectedProject.title}
                  className="w-full h-full object-cover group-hover/media:scale-105 transition-transform duration-500"
                />
              ) : (
                <div className="w-full h-full flex flex-col items-center justify-center p-6 relative overflow-hidden bg-gradient-to-br from-white/[0.04] via-transparent to-white/[0.02]">
                  {/* Subtle background grid & glow */}
                  <div className="absolute inset-0 grid-texture opacity-60 pointer-events-none" />
                  <div
                    className="absolute -top-10 -right-10 w-48 h-48 rounded-full blur-3xl opacity-20 pointer-events-none"
                    style={{ backgroundColor: selectedProject.accentColor }}
                  />

                  <div className="relative z-10 flex flex-col items-center text-center space-y-2">
                    <div
                      className="p-3 rounded-2xl border"
                      style={{
                        backgroundColor: `${selectedProject.accentColor}15`,
                        borderColor: `${selectedProject.accentColor}30`,
                        color: selectedProject.accentColor,
                      }}
                    >
                      <ImageIcon className="w-6 h-6" />
                    </div>
                    <p className="font-mono-tech text-xs sm:text-sm font-semibold text-white">
                      {selectedProject.title}
                    </p>
                    <span className="font-mono-tech text-[10px] sm:text-xs text-[#8e9192] px-3 py-1 rounded-full bg-white/5 border border-white/10">
                      1900 × 868 • Ratio 50:23
                    </span>
                  </div>
                </div>
              )}
            </div>

            {/* Metadata Grid */}
            <div className="grid grid-cols-2 gap-4 p-4 rounded-xl bg-white/5 border border-white/10 font-mono-tech text-xs">
              <div>
                <span className="text-[#8e9192] uppercase block mb-1">Role</span>
                <span className="text-white font-semibold flex items-center gap-1.5">
                  <UserCheck className="w-3.5 h-3.5 text-[#3B82F6]" />
                  {selectedProject.role}
                </span>
              </div>
              <div>
                <span className="text-[#8e9192] uppercase block mb-1">Timeline</span>
                <span className="text-white font-semibold flex items-center gap-1.5">
                  <Calendar className="w-3.5 h-3.5 text-[#8B5CF6]" />
                  {selectedProject.timeline}
                </span>
              </div>
            </div>

            {/* Overview */}
            <div>
              <h4 className="font-display text-sm font-bold text-white mb-2 uppercase tracking-wider">
                Overview
              </h4>
              <p className="font-sans text-sm text-[#c4c7c8] leading-relaxed">
                {selectedProject.description}
              </p>
              {selectedProject.additionalContext && (
                <p className="font-sans text-xs italic text-[#8e9192] mt-2">
                  {selectedProject.additionalContext}
                </p>
              )}
            </div>

            {/* Key Contributions */}
            {selectedProject.contributions && (
              <div>
                <h4 className="font-display text-sm font-bold text-white mb-3 uppercase tracking-wider">
                  Engineering Scope &amp; Contributions
                </h4>
                <ul className="space-y-2 font-sans text-sm text-[#c4c7c8]">
                  {selectedProject.contributions.map((c, i) => (
                    <li key={i} className="flex items-start gap-2.5">
                      <CheckCircle className="w-4 h-4 text-[#10B981] mt-0.5 shrink-0" />
                      <span>{c}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Tech Stack */}
            <div>
              <h4 className="font-display text-sm font-bold text-white mb-3 uppercase tracking-wider">
                Technologies Used
              </h4>
              <div className="flex flex-wrap gap-2">
                {selectedProject.tech.map((t) => (
                  <span
                    key={t}
                    className="font-mono-tech text-xs px-3.5 py-1.5 rounded-lg bg-white/10 border border-white/10 text-white"
                  >
                    {t}
                  </span>
                ))}
              </div>
            </div>

            {/* Modal Footer Action */}
            <div className="pt-4 border-t border-white/10 flex justify-end">
              <button
                onClick={() => setSelectedProject(null)}
                className="bg-white/10 hover:bg-white/20 text-white font-sans text-xs font-semibold px-6 py-2.5 rounded-xl transition-colors"
              >
                Close Case Study
              </button>
            </div>

          </div>
        </div>
      )}

    </section>
  );
}

